### ISSUE TITLE
It must be possible to use PCRaster with Python 3

### ISSUE THREAD

**Issue by kordejong** [pcraster/pcraster#101]
Make this configurable. See pybind11's CMakeLists.txt for inspiration.

**Comment by kordejong** [comment]
Verify all Python modules are valid Python3 modules:

    python -m py_compile <script>.py

**Comment by kordejong** [comment]
Most/all Python scripts are ported to Python 3 and are backwards compatible with Python 2. PCRaster builds, but a number of unit tests fail. Most/all of them are related to arrayed_variables, modelling_framework and modflow. Re-assigning the ticket to the expert on those projects.

See also `devbase/script/check_python_code_style.py`

**Comment by OliverSchmitz** [comment]
Solved while working on the new windows build
