### ISSUE TITLE
Must clone map before using numpy2pcr?

### ISSUE THREAD

**Issue by uttu90** [pcraster/pcraster#195]
Hi everyone,
I am doing one project with Python and Gdal .tiff files. When I use pcraster Python, I have to have at least one .map file to clone before using numpy2pcr function. Do I have another approach?

**Comment by uttu90** [comment]
Is there any helpful guide?

**Comment by OliverSchmitz** [comment]
You could use setclone with the clone properties as arguments to create a clone map at runtime, see
http://pcraster.geo.uu.nl/pcrahttp://pcraster.geo.uu.nl/pcraster/4.2.0/documentation/python/reference.html#pcraster._pcraster.setclonester/4.2.0/documentation/python/reference.html#pcraster._pcraster.setclone

**Comment by hatu90** [comment]
It's great answer!

**Comment by Imroz1** [comment]
Hi everyone
I am working on SPHY model and right now stuck in making clone map can anyone guide me.

**Comment by edwinkost** [comment]
> 

You can create a clone (pcraster) map using the "mapattr" command: https://pcraster.geo.uu.nl/pcraster/4.3.2/documentation/pcraster_manual/sphinx/app_mapattr.html

**Comment by Imroz1** [comment]
I wanted to know one thing. If any of you could tell me, I would be grateful.
I am not able to setup the model. Some interfaces are also not opening properly. I have downloaded all the manuals for SPHY but am confused on where to start.
Where should I start? Since this is my first modeling project, I need a little guidance from you guys.

**Comment by Imroz1** [comment]
Hello guys 
Please help me 
Any one can tell me how to prepare Input data set for the Trisuli case Study because when I had download Case study data from SPHY portal its just output data might be I am wrong, so please help me asap.

**Comment by kordejong** [comment]
@Imroz1 Please don't hijack an old ticket on GH about the numpy2pcr operation for asking questions. See the Support section on the [PCRaster home page](https://pcraster.geo.uu.nl/) for options for getting help, reporting bugs, etc.
