### ISSUE TITLE
ifthen does not work with nonspatial condition, ifthenelse does

### ISSUE THREAD

**Issue by kordejong** [pcraster/pcraster#229]
Repro case 1:

    setclone("clone.map")
    report(ifthen(0, scalar(5)), "result.map")

`result.map` is filled with uninitialized values. I expected it to be filled with no-data values.

Repro case 2:

    setclone("clone.map")
    report(ifthen(1, scalar(5)), "result.map")

`result.map` is filled with unititialized values. I expected it to be filled with 5.

Note that using `ifthenelse` works fine:

    setclone("clone.map")
    report(ifthenelse(1, scalar(5), scalar(4)), "result.map")

Tested with classic `ifthen`/`ifthenelse`.

Test snippet:

    setclone("clone.map")
    condition = boolean(0)  # <-- This doesn't work in ifthen case
    condition = spatial(boolean(0))  # <-- This works fine
    true_clause = scalar(5)
    false_clause = scalar(999)

    report(
        ifthen(condition, true_clause),
        "if_then.map")
    report(
        ifthenelse(condition, true_clause, false_clause),
        "if_then_else.map")

**Comment by OliverSchmitz** [comment]
Another one:

from pcraster import *
setclone(10,10,1,1,1)

b = ifthen(boolean(0)==1, boolean(1))
aguila(b)
