### ISSUE TITLE
memory leak in pcr2numpy

### ISSUE THREAD

**Issue by visr** [pcraster/pcraster#233]
In the 4.2.0 release the snippet below blows up very quickly taking all the memory. In 4.1.0 it keeps the memory at a low constant value.

```python
import pcraster as pcr
dem = pcr.readmap("dem.map")
while True:
    pcr.pcr2numpy(dem, 0)
```

`dem.map` in this case is a 1 MB Float32 map.

I came to this after trying to find why memory use kept increasing significantly every timestep in a wflow run using 4.2.0, whereas this was stable in 4.1.0.

**Comment by OliverSchmitz** [comment]
Thanks for reporting, but I can't reproduce it yet. Can you please provide operating system, Python and NumPy versions used?

**Comment by visr** [comment]
Ah yes sorry. OS is Windows 7, Python 3.6 and I believe latest NumPy, will check when I am on my PC.

**Comment by edwinkost** [comment]
I use linux (cartesius) and I experience the same problem (with pcraster 42). 

Please check this: https://github.com/edwinkost/various_issues/tree/master/memory_leak
- Running the script "repro_edwin.py" will show this memory leak problem. 
- A log file is also given: "memory.col"

**Comment by OliverSchmitz** [comment]
Thank you both. Works without trouble on my Linux machine ;-)
But indeed, both scripts fail on Windows, Edwin's on a different Linux box. I have sufficient reproducible cases fttb...

**Comment by visr** [comment]
I just tried the 4.2.1 binary from http://pcraster.geo.uu.nl/downloads/latest-release/, and it works like a charm.
Thanks!
