### ISSUE TITLE
Linking error: _pcraster.so

### ISSUE THREAD

**Issue by BenjaminFTurner** [pcraster/pcraster#248]
Linking error: _pcraster.so. PCRaster 4.2.1. Ubuntu 18.04. Python 3.

Scanning dependencies of target _pcraster
[ 70%] Building CXX object source/pcraster_python/CMakeFiles/_pcraster.dir/numpy_conversion.cc.o
[ 70%] Building CXX object source/pcraster_python/CMakeFiles/_pcraster.dir/PCRaster.cc.o
[ 70%] Building CXX object source/pcraster_python/CMakeFiles/_pcraster.dir/value_scale_traits.cc.o
[ 70%] Building CXX object source/pcraster_python/CMakeFiles/_pcraster.dir/pickle.cc.o
[ 70%] Linking CXX shared library ../../bin/pcraster/_pcraster.so
CMakeFiles/_pcraster.dir/PCRaster.cc.o: In function `init_pcraster':
PCRaster.cc:(.text+0xe6f): undefined reference to `boost::python::detail::init_module(char const*, void (*)())'
collect2: error: ld returned 1 exit status
source/pcraster_python/CMakeFiles/_pcraster.dir/build.make:203: recipe for target 'bin/pcraster/_pcraster.so' failed
make[2]: *** [bin/pcraster/_pcraster.so] Error 1
CMakeFiles/Makefile2:2386: recipe for target 'source/pcraster_python/CMakeFiles/_pcraster.dir/all' failed
make[1]: *** [source/pcraster_python/CMakeFiles/_pcraster.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by OliverSchmitz** [comment]
Hello Benjamin,
I assume this is related to newer boost versions. A bit hacky, but can you try to replace the file 
environment/cmake/PCRasterConfiguration.cmake
with this one and see whether that fixes the issue?
https://github.com/pcraster/pcraster/blob/8e3b923162285e642830d6071efd4198ccd4b7a4/environment/cmake/PCRasterConfiguration.cmake

**Comment by BenjaminFTurner** [comment]
Thanks for your help! There is no urgency in this for me. I'm just checking out various hydrologic modelling options. Actually, the model that I'm looking at, SPHY, doesn't even use the latest PCRaster and doesn't run on Linux, so it probably isn't suitable for my purpose. Hence, I may not attempt to compile PCRaster again.

Anyway, after applying your fix, there is another error:

Scanning dependencies of target pcraster_old_calc
[ 55%] Linking CXX shared library ../../bin/libpcraster_old_calc.so
/usr/bin/ld: cannot find -lBoost::math_c99
collect2: error: ld returned 1 exit status
source/pcraster_old_calc/CMakeFiles/pcraster_old_calc.dir/build.make:402: recipe for target 'bin/libpcraster_old_calc.so' failed
make[2]: *** [bin/libpcraster_old_calc.so] Error 1
CMakeFiles/Makefile2:2237: recipe for target 'source/pcraster_old_calc/CMakeFiles/pcraster_old_calc.dir/all' failed
make[1]: *** [source/pcraster_old_calc/CMakeFiles/pcraster_old_calc.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by OliverSchmitz** [comment]
ah, I missed that, we continued to further reduce dependencies (ie boost math) in master, so mixing files from master and 4.2 branch does not work any more smoothly. We need to fix the boost detection in the 4.2 branch properly...

**Comment by OliverSchmitz** [comment]
Incorporated into the 4.2 branch
