### ISSUE TITLE
Detect Python for installation on Linux (docs update)

### ISSUE THREAD

**Issue by nuest** [pcraster/pcraster#271]
(Not sure this is the right forum, but afaics the page at http://pcraster.geo.uu.nl/getting-started/pcraster-on-linux/ is not generated from a repo, otherwise happy to make a PR.)

I have a suggestion to change the installation instructions at http://pcraster.geo.uu.nl/getting-started/pcraster-on-linux/ after trying to install PCRaster on Ubuntu in a virtual environment:

- Add a step before the `cmake ...` step that installs required Python modules, i.e. `pip install -U numpy docopt`
- Change the `cmake` step to detect the current Python
```
cmake -DFERN_BUILD_ALGORITHM:BOOL=TRUE -DCMAKE_INSTALL_PREFIX:PATH=$HOME/pcraster -DPYTHON_EXECUTABLE:FILEPATH=$(which python) ..
```

The rest of the instructions worked fine.

**Comment by OliverSchmitz** [comment]
Hello,
thanks for the suggestion, fine to add website related tickets here as well. We incorporated them into the page.
