### ISSUE TITLE
Build PCRaster without Qt libs/Aguila

### ISSUE THREAD

**Issue by domeniconappo** [pcraster/pcraster#298]
Hi,
most of the times we don't need Aguila software.
If there is a way to skip its build, installation would be simplified because in this case there is no need to install deps like lib Qt/Qtw etc.

Furthermore, docker images would be smaller.

I haven't found a way to build PCRaster without Aguila. Any hint?
Thank you in advance!!!

**Comment by OliverSchmitz** [comment]
Hi,
Qt will be required even without building Aguila. The upcoming release has a configuration flag to enable/disable building Aguila, and in any case no longer a dependency on qwt. I hope it's a matter of days to get that finalised...

**Comment by domeniconappo** [comment]
@OliverSchmitz 
Thank you! Looking forward for next release.

**Comment by OliverSchmitz** [comment]
4.3 is out, the 'Changes' page of the documentation should give an indication how to build a package without Aguila.

**Comment by domeniconappo** [comment]
@OliverSchmitz Thanks! I've got the release announcement this morning :) Excellent!
