### ISSUE TITLE
PCRaster on MacOs

### ISSUE THREAD

**Issue by corentincarton** [pcraster/pcraster#301]
Hi,

I'm trying to build PCRaster on MacOS and I got the following error:

> CMake Error at devbase/cmake/PeacockPlatform.cmake:90 (message):
  Add compiler id for AppleClang
Call Stack (most recent call first):
  environment/cmake/PCRaster.cmake:6 (include)
  CMakeLists.txt:49 (include)

I managed to fix the error by adding the following lines in the files
> source/fern/devbase/cmake/PeacockPlatform.cmake
devbase/cmake/PeacockPlatform.cmake
```
elseif(peacock_compiler_id STREQUAL "AppleClang")
    set(peacock_compiler_id "clang")
```
But I still have to check if everything compiles properly. Do you have guidelines to compile on MacOS?

**Comment by OliverSchmitz** [comment]
I think you try with the XCode compiler, right? I never used that. Can you use MacPorts or Homebrew? You could also just install PCRaster with conda in case you want to avoid compiling.

**Comment by corentincarton** [comment]
I managed to compile fine by adding the two lines in the files so it could be interesting to add them to the source.
I didn't know you had a Conda recipe, that's great! I'll try it right away.

Thanks for your help,
Corentin
