### ISSUE TITLE
How to print the header information of PCRaster map file

### ISSUE THREAD

**Issue by yellowpuppy** [pcraster/pcraster#319]
I have a project with all .tif files，so pcr.setclone() should be done before transforming the numpy array to PCRaster map (#195). however, I have no idea that the parameters in setclone() I have set are correct. Therefore I want to print the header information of a example .map file so I can see how it works to help me set the parameters. But how can I check the header information of a .map file？

**Comment by kordejong** [comment]
Hi @yellowpuppy , have look at the mapattr PCRaster command. It can print information about a .map raster. Also, GDAL's gdalinfo command can do the same.

In the future, you may want to direct usability questions to the PCRaster mailinglist. You will likely get answers more quickly than here. Github issues are meant for software bugs and new features we want to implement.
