### ISSUE TITLE
Incorrect handling of quotes with pcr.aguila

### ISSUE THREAD

**Issue by OliverSchmitz** [pcraster/pcraster#325]
this used to work:
pcr.aguila('dem.map + anArea.map')

**Comment by kordejong** [comment]
I am not sure whether that is true. Anyway, this used to work as well:

```bash
# Show dem.map + ldd.map and soil.map (two windows)
pcr.aguila(["dem.map", "ldd.map"], "soil.map")
```

**Comment by kordejong** [comment]
De aguila functie is gemaakt voor het bekijken van Python variabelen. Dus geen referenties naar rasters op disk enzo. Alleen Python variabelen. Je bent aan het scripten en wil ff kijken hoe een raster eruit ziet. `aguila([dem, ldd], soil)`. Al het andere werkt toevallig.

**Comment by OliverSchmitz** [comment]
werkte... ik heb het toen per ongeluk gesloopt
dit werkt nog wel
aguila('--timesteps=[1,181,1]','q')
