### ISSUE TITLE
Error building in Arch Linux

### ISSUE THREAD

**Issue by samtux** [pcraster/pcraster#342]
I am trying to build the instructions for PCRaster compilation on Arch Linux: 

https://gist.github.com/samtux/df95d42cf23d1b65c4fd568ab793e71d

However I always get an error, which I don't know if it is related to the version or missing one of the dependencies:

https://gist.github.com/samtux/788165dc66cbba00430dcfe1a8c8f266/raw/aaa0e49047018beab88ac6a1d27d163f16477af0/pcraster.log

I appreciate any help to solve it.

OS: Arch Linux x64
GCC: 11.1.0

**Comment by OliverSchmitz** [comment]
Can you try http://pcraster.geo.uu.nl/pcraster/packages/src/pcraster-4.3.2.tar.bz2 (sha256: 3ac7d3186f4ba876a5a8e8d8bf10b109bdc7b5b33d84d26bab0948f29deac2a7)? It builds with Boost 1.74 and should also work with 1.76
