### ISSUE TITLE
Access to previous versions of pcraster

### ISSUE THREAD

**Issue by corentincarton** [pcraster/pcraster#355]
Hi,

I would need a version of PCRaster compatible with Python 2 as one of my dependencies (requiring PCRaster) is not compatible with Python 3. If I remember correctly, PCRaster 4.1.0 was compatible with Python 2 but I can't find the sources on your website or GitHub. Would it be possible to provide me with the latest version of PCRaster compatible with Python 2? I would need to make it work within a conda environment so any tips to update the conda recipe from conda-forge for this version would be greatly appreciated!

Thanks,
Corentin

**Comment by OliverSchmitz** [comment]
Hi, not sure if this is still necessary, but you could try to build the 4.2 branch, I think that still has support for Python 2.7. Although I strongly recommend to not use Python 2.7 ;-)
I close this for now, you can reopen if you really need this
