### ISSUE TITLE
Slope length function very slow

### ISSUE THREAD

**Issue by corentincarton** [pcraster/pcraster#360]
Hi,

We are working on an inundation model that requires to run the slopelength function on very big catchments (the Amazon is the biggest one, with 30k x 35k grid points). The problem we have is that the algorithm is very very slow... it takes more than a week to run just that function, which is not practical as we will have to run this algorithm on the whole planet (for the GloFAS system).

From what I understand, the Slopelength function calls the Longest() function for all the grid points. This seems very redundant... wouldn't it be possible to speedup the computation by using a more global approach? We would be happy to discuss the algorithm with you but we are not familiar with the PCRaster internal data structure, so we can't really implement this algorithm ourselves... we would need your help.

Best,
Corentin

**Comment by kordejong** [comment]
I Corentin,

Thanks for reporting and offering help! I am not familiar yet with the algorithm used by the slopelength operation in PCRaster. I do know that it is unlikely that our team will change its implementation in the PCRaster software. All new developments happen in the new LUE modelling package which we are developing specifically for the case of very large problems. See also https://lue.computationalgeography.org/

In the future, PCRaster models can be ported to the new LUE framework, which offers performance and scalability gains. LUE models can be executed unchanged on both laptops (shared memory, small datasets) and computer clusters (distributed memory, large datasets). See also https://lue.computationalgeography.org/doc/pcraster/status.html

As you see, LUE is work in progress and not ready for general use yet. The slopelength operation is on our list of operations to add to LUE in the future. I understand that this is of no help for your current modelling development.

I will close this ticket now. In case you happen to have good ideas about an efficient and scalable implementation of the slopelength operation, then don't hesitate to contact us directly (contact info on the LUE website: https://lue.computationalgeography.org). Also, you may be interested in our last two publications about the LUE framework:

- An environmental modelling framework based on asynchronous many-tasks: scalability and usability (https://doi.org/10.1016/j.envsoft.2021.104998)
- Scalability and composability of flow accumulation algorithms based on asynchronous many-tasks (https://doi.org/10.1016/j.cageo.2022.105083)

Best regards,
Kor
