### ISSUE TITLE
PCRaster Install Issue

### ISSUE THREAD

**Issue by TLewis87** [pcraster/pcraster#363]
I keep trying to install PCRaster Tool Plugin and I get the same message "PCRaster must be installed and available in the current Python environment before the PCRaster algorithms can be used. Please see the plugin documentation for further details on how to install PCRaster."

Then I follow the instruction which requires me to go into OSGeo3w Setup, which I follow exactly (screenshots). The OSGeo3W shows I have the current version of PCRaster (4.3.3.5). However, each time I try to reinstall PCRASTER 4.3.3.5, I get an error that reads "Package: Unknown Package shell.bat exit code 1".

Does anyone have suggestions on what I'm doing wrong so I can can properly install PCRaster and proceed with installing the PCRaster Tool Plugin?

![Script Error](https://user-images.githubusercontent.com/111711982/185815162-c1542a34-2c67-4fe3-a29f-9acb638d7cee.jpg)
![setup](https://user-images.githubusercontent.com/111711982/185815164-566c864d-9ebd-4c49-aaac-d78a2ded6db3.jpg)

**Comment by jvdkwast** [comment]
The bottom screenshot shows that PCRaster is installed, because it states "keep". I can't check if your error is caused by PCRaster or something else. Please check my troubleshooting videos to make sure you're using the QGIS version that belongs to the correct OSGeo4W Setup:
[https://youtu.be/2pEr5RoGAXc](https://youtu.be/2pEr5RoGAXc)

**Comment by Crones8** [comment]
Yep, same problem here. Followed the video, problem persists. on Qgis 3.28.10

**Comment by jvdkwast** [comment]
Issue can be closed. See https://github.com/jvdkwast/qgis-processing-pcraster/issues/61.
