### ISSUE TITLE
Configure fails with `Unknown CMake command "configure_python_extension"`

### ISSUE THREAD

**Issue by nilason** [pcraster/pcraster#384]
Attempting to configure PCRaster 4.4.1 (with CMake 3.24.4), fails with:
```
CMake Error at source/pcraster_moc/python/CMakeLists.txt:28 (configure_python_extension):
  Unknown CMake command "configure_python_extension".
```

https://github.com/pcraster/pcraster/blob/8f18c21608ed6cf2ab0a0c927770865fd19de280/source/pcraster_moc/python/CMakeLists.txt#L28-L30

The same failure occurs on:
https://github.com/pcraster/pcraster/blob/8f18c21608ed6cf2ab0a0c927770865fd19de280/source/mldd/python/CMakeLists.txt#L16-L18

Following the removal/commenting out the two uses of `configure_python_extension´ the configure succeeds.

**Comment by OliverSchmitz** [comment]
Thanks for reporting! Interesting, this should have failed already for a long time...
Could you provide a pull request?

**Comment by nilason** [comment]
> Thanks for reporting! Interesting, this should have failed already for a long time...

One would think so. I only now tried to build PCRaster in the process to add it as a [package to MacPorts](https://ports.macports.org/port/pcraster/).

> Could you provide a pull request?

I see similar CMake code is commented out [elsewhere](https://github.com/search?q=repo%3Apcraster%2Fpcraster%20configure_python_extension&type=code), my take they can all be removed!? Sure, I'll prepare a PR.

**Comment by OliverSchmitz** [comment]
yes, they are no longer required.
And MacPorts, nice :-) Thanks for the effort! Please let us know if you have further issues
