### ISSUE TITLE
[Bug]: PCRaster plugins not working after being installed even though I did the OSGeo4w thing previously

### ISSUE THREAD

**Issue by Crones8** [pcraster/pcraster#406]
### Describe the bug

Version of QGIS is 3.28.10.

I've seen this issue being asked here in github before:

![image](https://github.com/user-attachments/assets/1feaabee-500f-4acd-8449-f0955d226075)

Mostly people are redirected to https://jvdkwast.github.io/qgis-processing-pcraster/, in which the installation of PCRaster through OSGeo4w is suggested (watched the video and everything):

![image](https://github.com/user-attachments/assets/ccba101d-fece-450d-ac8c-946ef19eafc4)

I already did this, and succesfully, as shown here:

![image](https://github.com/user-attachments/assets/e2d9a3ea-876d-4565-9eea-2078858b1261)

So, even though I've followed the suggested troubleshooting steps, software still will not work.

Please Help

### Expected behaviour

Just want to be able to use the plugins 

### Steps to reproduce

I'm not sure, having QGIS 3.28.10 and trying to install the PCRaster Tool I guess?

### Additional information

Tried it on a QGIS installation that was 3.22.8 I think didn't work either.

**Comment by OliverSchmitz** [comment]
Is the standalone install from PCRaster working? I.e. the command line applications and Python module? Then it's perhaps a path setting in the plugin.
Did you try here https://github.com/jvdkwast/qgis-processing-pcraster? More people may be able to help there wrt the plugin.

**Comment by Crones8** [comment]
I asked on the other topic as well, but haven't been able to solve it through there.

What do you mean with the standalone install? the OSGeo4W install? How can I test it (line application and Python module)? 

Cheers and thank you.

**Comment by OliverSchmitz** [comment]
Yes, I refer to the OSGeo4W install. I'm not a Windows user and don't know the OSGeo4W exactly, but I assume it either has its own Windows command prompt, or will modify the default command prompt (i.e. cmd) to find the OSGeo applications.
In such a command prompt, can you execute
`pcrcalc`
and
`python -c 'import pcraster;print(pcraster.__version__)'`
? Both should show the current version number of PCRaster if everything works properly

**Comment by Crones8** [comment]
You mean in QGis? Because the OSGeo4W, to my knowledge, doesn't have a command prompt. 

I'm no expert, OSGeo4W it's just a simple UI with many "Continue" and "Next" buttons, where the UI let's you choose what to install. Later, after installing, I'm guessing the only way to use commands with this installations is through the python console in QGis, like this:

![image](https://github.com/user-attachments/assets/4a4304d0-de47-49fa-9d10-f8c1ab5c034d)

However, trying any of the 2 commands you've just given me end up in errors.

Cheers and thank you.

**Comment by OliverSchmitz** [comment]
ah, no, I meant the good old DOS command prompt, you get it when typing `cmd` in the start menu. There you could try both commands.
but in that Python console you show in the screenshot, what does happen when you type `import pcraster`
does it find the module at all, or does it fail at import? perhaps you can state the message that is then printed

**Comment by Crones8** [comment]
Hello Oliver,

It does not find it in the python console:

![image](https://github.com/user-attachments/assets/87c1345b-bd1d-460d-8086-d475b54e70d0)

Trying the command in the cmd, when being in the osgeo4w or qgis bin folder always gives the same error:

![image](https://github.com/user-attachments/assets/be9a6661-39f8-4f55-bf14-a7c09670fd13)

It prompts 3 times, maybe this is where the problem is.

Tried reinstalling QT5, the folder appears but problem now shows gdal309.dll error:

![image](https://github.com/user-attachments/assets/32848b6c-ef08-4b72-92d9-70b73d822a29)

I'm not sure how to fix this.

**Comment by Crones8** [comment]
Haven't tried it no, eventually will use if if necessary, but don't really want to be installing anything else.

**Comment by Crones8** [comment]
Hans helped to get it working, so I consider it to be closed (even though the commands still do not work in CMD) I'll copy paste what I said on the other post here so the answer is in both places:

"So, to anyone asking how we "fixed" this, here it is:

The reason I say "fixed" it's because Hans helped me to get 2 instances of QGIS working in my PC 3.28.10 and 3.40.1 (without uninstalling either one), and now I can effectively use PCRaster Tools on 3.40.1, however, I couldn't get it to work in 3.28.10, so yeah, I can now use PCRaster Tools, just not on the older version of QGIS.

Hans tells me it's probably because the version of PCRaster that is installed through OSGeo4W only works with the latest or some of the latest version of QGIS, and not with legacy versions, though this is not proved yet.

Hope this helps anyone, and special thanks to Hans for taking the time, even while being on a trip, to help me, he is truly a person who cares to help."

Cheers and thank you for taking the time to help Oliver
